server:
  port: 16014


spring:
  cloud:
    nacos:
      discovery:
        server-addr: 118.25.36.41:8848
    sentinel:
      transport:
        port: 18763
        dashboard: 127.0.0.1:8748
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
    service:
      name: provider

  sleuth:
    sampler:
      probability: 1 #设置采样率默认为 0.1 注意之前的版本是percentage 新版本中更换为 probability
feign:
  sentinel:
    enabled: true

test:
  config:
    refresh: false

swagger:
    enable: true
